using smpc_accounting_app.Models.Hris;
using smpc_accounting_app.Services.Helpers;
using smpc_accounting_app.Services.Hris;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Windows.Forms;

namespace smpc_accounting_app.Pages.Setup.Hris
{
    // HRIS Payroll (HRIS group) - pay runs generated by the HRIS GraphQL API
    // from the employee master + APPROVED timesheets. Statutory deductions are
    // server-computed DEFAULTS; the earning/deduction columns stay editable per
    // item while the run is DRAFT (the accountant owns the final figures).
    // APPROVED locks the run (Approve/Reopen need HRIS_PAYROLL_APPROVAL).
    //
    // Document-style form like the other HRIS pages. Constructor stays
    // I/O-free (RoutesService instantiates pages eagerly).
    public partial class PayrollRunPage : UserControl
    {
        private List<HrisPayrollRunModel> _runs = new List<HrisPayrollRunModel>();
        private int _currentIndex = -1;
        private bool _isNewMode;
        private bool _editMode;
        private bool _loaded;

        private HrisPayrollRunModel Current =>
            _currentIndex >= 0 && _currentIndex < _runs.Count ? _runs[_currentIndex] : null;

        private TextBox txt_periodStart, txt_periodEnd, txt_cutYear, txt_cutMonth, txt_cutPeriod,
            txt_payDate, txt_notes, txt_status, txt_totals, txt_genNotes;
        private ComboBox cmb_frequency;

        // Columns the accountant may override while DRAFT (GraphQL field names).
        private static readonly string[] OverrideColumns =
            { "basicPayAmount", "otPay", "ndPay", "holidayPremiumPay", "allowanceAmount", "otherEarnings",
              "sssEe", "philhealthEe", "pagibigEe", "withholdingTax", "tardinessDeduction", "otherDeductions" };

        public PayrollRunPage()
        {
            InitializeComponent();
            BuildHeaderFields();
            BuildItemsGrid();
            SetEditMode(false);
        }

        // ------------------------------------------------------------ layout

        private void BuildHeaderFields()
        {
            var t = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                ColumnCount = 2,
                AutoScroll = true,
                Padding = new Padding(10)
            };
            t.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 190F));
            t.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 560F));

            cmb_frequency = new ComboBox { DropDownStyle = ComboBoxStyle.DropDownList };
            cmb_frequency.Items.AddRange(new object[] { "SEMI_MONTHLY", "WEEKLY", "MONTHLY" });
            cmb_frequency.SelectedIndex = 0;
            t.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            t.Controls.Add(new Label { Text = "PAY FREQUENCY *", AutoSize = true, Anchor = AnchorStyles.Left, Padding = new Padding(0, 4, 0, 0) });
            cmb_frequency.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            t.Controls.Add(cmb_frequency);
            txt_cutYear = PlaceText(t, "CUTOFF YEAR");
            txt_cutMonth = PlaceText(t, "CUTOFF MONTH (1-12)");
            txt_cutPeriod = PlaceText(t, "PERIOD NO (wk 1-4 / semi 1-2 / mo 1)");
            txt_periodStart = PlaceText(t, "PERIOD START (or type dates)");
            txt_periodEnd = PlaceText(t, "PERIOD END (YYYY-MM-DD)");
            txt_payDate = PlaceText(t, "PAY DATE (YYYY-MM-DD)");
            txt_notes = PlaceText(t, "NOTES");
            txt_status = PlaceText(t, "STATUS");
            txt_status.ReadOnly = true;
            txt_totals = PlaceText(t, "TOTALS");
            txt_totals.ReadOnly = true;
            txt_genNotes = PlaceText(t, "GENERATION NOTES");
            txt_genNotes.ReadOnly = true;

            pnl_header.Controls.Add(t);
        }

        private TextBox PlaceText(TableLayoutPanel t, string label)
        {
            var txt = new TextBox { BackColor = System.Drawing.Color.Gainsboro };
            t.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            t.Controls.Add(new Label { Text = label, AutoSize = true, Anchor = AnchorStyles.Left, Padding = new Padding(0, 4, 0, 0) });
            txt.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            t.Controls.Add(txt);
            return txt;
        }

        private void BuildItemsGrid()
        {
            void ReadOnlyCol(string name, string header, int width)
            {
                var col = new DataGridViewTextBoxColumn { Name = name, HeaderText = header, Width = width, ReadOnly = true };
                col.DefaultCellStyle.BackColor = System.Drawing.Color.Gainsboro;
                dgv_items.Columns.Add(col);
            }
            void EditCol(string name, string header, int width)
            {
                dgv_items.Columns.Add(new DataGridViewTextBoxColumn { Name = name, HeaderText = header, Width = width });
            }

            dgv_items.Columns.Add(new DataGridViewTextBoxColumn { Name = "id", Visible = false });
            ReadOnlyCol("employee", "EMPLOYEE", 190);
            ReadOnlyCol("rateType", "RATE", 70);
            ReadOnlyCol("basicRate", "BASIC RATE", 85);
            ReadOnlyCol("daysWorked", "DAYS", 50);
            ReadOnlyCol("otHours", "OT HRS", 60);
            ReadOnlyCol("ndHours", "ND HRS", 60);
            ReadOnlyCol("lateUtMinutes", "LATE/UT", 60);
            EditCol("basicPayAmount", "BASIC PAY", 85);
            EditCol("otPay", "OT PAY", 70);
            EditCol("ndPay", "ND PAY", 70);
            EditCol("holidayPremiumPay", "HOLIDAY PAY", 90);
            EditCol("allowanceAmount", "ALLOWANCE", 85);
            EditCol("otherEarnings", "OTHER EARN", 85);
            EditCol("sssEe", "SSS", 70);
            EditCol("philhealthEe", "PHILHEALTH", 85);
            EditCol("pagibigEe", "PAG-IBIG", 70);
            EditCol("withholdingTax", "W/TAX", 80);
            EditCol("tardinessDeduction", "TARDINESS", 80);
            EditCol("otherDeductions", "OTHER DED", 80);
            ReadOnlyCol("grossPay", "GROSS", 85);
            ReadOnlyCol("deductionsTotal", "DEDUCTIONS", 90);
            ReadOnlyCol("netPay", "NET PAY", 90);
            dgv_items.Columns.Add(new DataGridViewTextBoxColumn { Name = "remarks", HeaderText = "REMARKS", AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill });
        }

        // ------------------------------------------------------------ loading

        private async void PayrollRunPage_Load(object sender, EventArgs e)
        {
            if (_loaded) return;
            _loaded = true;
            try
            {
                Helpers.Loading.ShowLoading(dgv_items, "Fetching data...");
                await LoadData();
            }
            catch (Exception ex)
            {
                Helpers.ShowDialogMessage("error", $"Failed to load: {ex.Message}");
            }
            finally
            {
                Helpers.Loading.HideLoading(dgv_items);
            }
        }

        private async System.Threading.Tasks.Task LoadData(int? keepId = null)
        {
            var result = await HrisPayrollService.GetPayrollRunsAsync();
            if (result.HasErrors)
            {
                Helpers.ShowDialogMessage("error", result.ErrorMessage);
                return;
            }
            _runs = result.Data.PayrollRuns.Items ?? new List<HrisPayrollRunModel>();

            if (keepId.HasValue)
            {
                _currentIndex = _runs.FindIndex(x => x.Id == keepId.Value);
                if (_currentIndex < 0 && _runs.Count > 0) _currentIndex = 0;
            }
            else
            {
                _currentIndex = _runs.Count > 0 ? 0 : -1;
            }
            ShowCurrent();
        }

        private void ShowCurrent()
        {
            if (Current != null) BindDetail(Current);
            else ClearDetail();
            lbl_record.Text = _runs.Count == 0 ? "0 / 0" : $"{_currentIndex + 1} / {_runs.Count}";
            UpdateNavButtons();
        }

        private void UpdateNavButtons()
        {
            btn_prev.Enabled = !_editMode && _currentIndex > 0;
            btn_next.Enabled = !_editMode && _currentIndex >= 0 && _currentIndex < _runs.Count - 1;
            btn_search.Enabled = !_editMode;
            btn_regenerate.Enabled = !_editMode && Current != null && Current.Status == "DRAFT";
            btn_approve.Enabled = !_editMode && Current != null && Current.Status == "DRAFT";
            btn_reopen.Enabled = !_editMode && Current != null && Current.Status == "APPROVED";
            btn_printPayslips.Enabled = !_editMode && Current != null;
            btn_printRegister.Enabled = !_editMode && Current != null;
            btn_printRemittance.Enabled = !_editMode && Current != null;
        }

        private void BindDetail(HrisPayrollRunModel run)
        {
            cmb_frequency.Text = string.IsNullOrEmpty(run.PayFrequency) ? "SEMI_MONTHLY" : run.PayFrequency;
            txt_cutYear.Text = run.CutoffYear > 0 ? run.CutoffYear.ToString() : "";
            txt_cutMonth.Text = run.CutoffMonth > 0 ? run.CutoffMonth.ToString() : "";
            txt_cutPeriod.Text = run.PeriodNo > 0 ? run.PeriodNo.ToString() : "";
            txt_periodStart.Text = run.PeriodStart;
            txt_periodEnd.Text = run.PeriodEnd;
            txt_payDate.Text = run.PayDate;
            txt_notes.Text = run.Notes;
            txt_status.Text = run.Status;
            txt_totals.Text = $"Employees: {run.EmployeeCount}   Gross: {run.TotalGross:n2}   Deductions: {run.TotalDeductions:n2}   Net: {run.TotalNet:n2}";
            txt_genNotes.Text = run.GenerationNotes;

            dgv_items.Rows.Clear();
            foreach (var item in run.Items)
            {
                string employee = item.Employee != null
                    ? $"{item.Employee.EmployeeNo} — {item.Employee.FirstName} {item.Employee.LastName}"
                    : item.EmployeeId.ToString();
                dgv_items.Rows.Add(item.Id, employee, item.RateType,
                    N(item.BasicRate), item.DaysWorked, N(item.OtHours), N(item.NdHours), item.LateUtMinutes,
                    N(item.BasicPayAmount), N(item.OtPay), N(item.NdPay), N(item.HolidayPremiumPay), N(item.AllowanceAmount), N(item.OtherEarnings),
                    N(item.SssEe), N(item.PhilhealthEe), N(item.PagibigEe), N(item.WithholdingTax),
                    N(item.TardinessDeduction), N(item.OtherDeductions),
                    N(item.GrossPay), N(item.DeductionsTotal), N(item.NetPay), item.Remarks);
            }
        }

        private static string N(decimal v) { return v.ToString("0.##", CultureInfo.InvariantCulture); }

        private void ClearDetail()
        {
            foreach (var txt in new[] { txt_periodStart, txt_periodEnd, txt_payDate, txt_notes, txt_totals, txt_genNotes })
            {
                txt.Text = "";
            }
            cmb_frequency.Text = "SEMI_MONTHLY";
            txt_cutYear.Text = DateTime.Now.Year.ToString();
            txt_cutMonth.Text = DateTime.Now.Month.ToString();
            txt_cutPeriod.Text = "";
            txt_status.Text = "DRAFT";
            dgv_items.Rows.Clear();
        }

        // ------------------------------------------------------------ edit mode

        private void SetEditMode(bool enable, bool isNewMode = false)
        {
            _editMode = enable;
            _isNewMode = isNewMode;

            btn_save.Visible = enable;
            btn_cancel.Visible = enable;
            btn_new.Visible = !enable;
            btn_edit.Visible = !enable;
            btn_regenerate.Visible = !enable;
            btn_approve.Visible = !enable;
            btn_reopen.Visible = !enable;
            btn_printPayslips.Visible = !enable;
            btn_printRegister.Visible = !enable;
            btn_printRemittance.Visible = !enable;

            cmb_frequency.Enabled = enable;
            txt_cutYear.ReadOnly = !enable;
            txt_cutMonth.ReadOnly = !enable;
            txt_cutPeriod.ReadOnly = !enable;
            txt_periodStart.ReadOnly = !enable;
            txt_periodEnd.ReadOnly = !enable;
            txt_payDate.ReadOnly = !enable;
            txt_notes.ReadOnly = !enable;

            // Items exist only after generation: overrides are editable when
            // editing an existing DRAFT run, never in new mode.
            dgv_items.ReadOnly = !(enable && !isNewMode);

            UpdateNavButtons();
        }

        private void btn_new_Click(object sender, EventArgs e)
        {
            ClearDetail();
            SetEditMode(true, isNewMode: true);
        }

        private void btn_edit_Click(object sender, EventArgs e)
        {
            if (Current == null)
            {
                Helpers.ShowDialogMessage("error", "No payroll run loaded. Use Search or New.");
                return;
            }
            if (Current.Status == "APPROVED")
            {
                Helpers.ShowDialogMessage("error", "This payroll run is approved and locked. Reopen it first.");
                return;
            }
            SetEditMode(true);
        }

        private void btn_cancel_Click(object sender, EventArgs e)
        {
            SetEditMode(false);
            ShowCurrent();
        }

        private void btn_prev_Click(object sender, EventArgs e)
        {
            if (_currentIndex <= 0) return;
            _currentIndex--;
            ShowCurrent();
        }

        private void btn_next_Click(object sender, EventArgs e)
        {
            if (_currentIndex >= _runs.Count - 1) return;
            _currentIndex++;
            ShowCurrent();
        }

        private void btn_search_Click(object sender, EventArgs e)
        {
            if (_runs.Count == 0)
            {
                Helpers.ShowDialogMessage("error", "No payroll runs yet. Use New to create one.");
                return;
            }
            using (var dialog = new SearchPayrollDialog(_runs))
            {
                if (dialog.ShowDialog(FindForm()) != DialogResult.OK || !dialog.SelectedRunId.HasValue) return;
                int index = _runs.FindIndex(x => x.Id == dialog.SelectedRunId.Value);
                if (index >= 0)
                {
                    _currentIndex = index;
                    ShowCurrent();
                }
            }
        }

        // ------------------------------------------------------------ save

        private async void btn_save_Click(object sender, EventArgs e)
        {
            btn_save.Enabled = false;
            btn_cancel.Enabled = false;
            try
            {
                bool hasCutoff = int.TryParse(txt_cutYear.Text, out int cutYear)
                    & int.TryParse(txt_cutMonth.Text, out int cutMonth)
                    & int.TryParse(txt_cutPeriod.Text, out int cutPeriod);
                if (!hasCutoff && (string.IsNullOrWhiteSpace(txt_periodStart.Text) || string.IsNullOrWhiteSpace(txt_periodEnd.Text)))
                {
                    Helpers.ShowDialogMessage("error", "Give a cutoff (year + month + period) or type the period dates.");
                    return;
                }
                var header = new Dictionary<string, object>
                {
                    { "payFrequency", cmb_frequency.Text },
                    { "notes", txt_notes.Text.Trim() },
                };
                if (hasCutoff)
                {
                    header["cutoffYear"] = cutYear;
                    header["cutoffMonth"] = cutMonth;
                    header["periodNo"] = cutPeriod;
                }
                else
                {
                    header["periodStart"] = txt_periodStart.Text.Trim();
                    header["periodEnd"] = txt_periodEnd.Text.Trim();
                }
                if (!string.IsNullOrWhiteSpace(txt_payDate.Text)) header["payDate"] = txt_payDate.Text.Trim();

                Helpers.Loading.ShowLoading(dgv_items, "Saving data...");

                string error;
                int? savedId = null;
                if (_isNewMode)
                {
                    var result = await HrisPayrollService.CreateAsync(header);
                    error = result.HasErrors ? result.ErrorMessage : null;
                    if (error == null) savedId = result.Data.CreatePayrollRun.Id;
                }
                else
                {
                    var result = await HrisPayrollService.UpdateAsync(Current.Id, header);
                    error = result.HasErrors ? result.ErrorMessage : null;
                    if (error == null)
                    {
                        savedId = Current.Id;
                        var overrides = CollectOverrides();
                        if (overrides == null) return; // parse error already shown
                        if (overrides.Count > 0)
                        {
                            var itemsResult = await HrisPayrollService.UpdateItemsAsync(Current.Id, overrides);
                            error = itemsResult.HasErrors ? itemsResult.ErrorMessage : null;
                        }
                    }
                }

                if (error != null)
                {
                    Helpers.ShowDialogMessage("error", error);
                    return;
                }

                Helpers.ShowDialogMessage("success", _isNewMode ? "Payroll run created and generated." : "Payroll run updated.");
                SetEditMode(false);
                await LoadData(savedId);
            }
            catch (Exception ex)
            {
                Helpers.ShowDialogMessage("error", $"Failed to save: {ex.Message}");
            }
            finally
            {
                btn_save.Enabled = true;
                btn_cancel.Enabled = true;
                Helpers.Loading.HideLoading(dgv_items);
            }
        }

        // Reads every row's override columns into PayrollItemOverrideInput dicts.
        // Returns null after showing a message when a cell fails to parse.
        private List<object> CollectOverrides()
        {
            var overrides = new List<object>();
            foreach (DataGridViewRow row in dgv_items.Rows)
            {
                var idValue = row.Cells["id"].Value;
                if (idValue == null) continue;
                var item = new Dictionary<string, object> { { "id", Convert.ToInt32(idValue) } };
                foreach (string column in OverrideColumns)
                {
                    string text = CellText(row, column);
                    if (string.IsNullOrWhiteSpace(text)) continue;
                    if (!decimal.TryParse(text, NumberStyles.Number, CultureInfo.InvariantCulture, out decimal value))
                    {
                        Helpers.ShowDialogMessage("error", $"{dgv_items.Columns[column].HeaderText} must be a number.");
                        return null;
                    }
                    item[column] = value;
                }
                item["remarks"] = CellText(row, "remarks");
                overrides.Add(item);
            }
            return overrides;
        }

        private static string CellText(DataGridViewRow row, string column)
        {
            var value = row.Cells[column].Value;
            return value == null ? "" : value.ToString().Trim();
        }

        // ------------------------------------------------------------ actions

        private async void btn_regenerate_Click(object sender, EventArgs e)
        {
            if (Current == null) return;
            var confirm = MessageBox.Show(
                "Regenerate this run's items from the current employee data and approved timesheets? Manual overrides will be discarded.",
                "Confirm Regenerate", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
            if (confirm != DialogResult.Yes) return;
            await RunAction(async () => { var r = await HrisPayrollService.RegenerateAsync(Current.Id); return r.Errors; }, "Payroll run regenerated.");
        }

        private async void btn_approve_Click(object sender, EventArgs e)
        {
            if (Current == null) return;
            var confirm = MessageBox.Show(
                "Approve this payroll run? It becomes locked. Review the statutory deduction defaults before approving.",
                "Confirm Approve", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
            if (confirm != DialogResult.Yes) return;
            await RunAction(async () => { var r = await HrisPayrollService.ApproveAsync(Current.Id); return r.Errors; }, "Payroll run approved.");
        }

        private async void btn_reopen_Click(object sender, EventArgs e)
        {
            if (Current == null) return;
            var confirm = MessageBox.Show(
                "Reopen this approved payroll run for correction?",
                "Confirm Reopen", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
            if (confirm != DialogResult.Yes) return;
            await RunAction(async () => { var r = await HrisPayrollService.ReopenAsync(Current.Id); return r.Errors; }, "Payroll run reopened.");
        }

        private async System.Threading.Tasks.Task RunAction(
            Func<System.Threading.Tasks.Task<List<GraphQLError>>> action, string successMessage)
        {
            try
            {
                Helpers.Loading.ShowLoading(dgv_items, "Saving data...");
                var errors = await action();
                if (errors != null && errors.Any())
                {
                    Helpers.ShowDialogMessage("error", string.Join("; ", errors.Select(x => x.Message)));
                    return;
                }
                Helpers.ShowDialogMessage("success", successMessage);
                await LoadData(Current.Id);
            }
            catch (Exception ex)
            {
                Helpers.ShowDialogMessage("error", $"Failed: {ex.Message}");
            }
            finally
            {
                Helpers.Loading.HideLoading(dgv_items);
            }
        }

        // ------------------------------------------------------------ printing

        private void btn_printPayslips_Click(object sender, EventArgs e)
        {
            if (Current == null) return;
            HrisPayrollPrinter.PreviewPayslips(Current, FindForm());
        }

        private void btn_printRegister_Click(object sender, EventArgs e)
        {
            if (Current == null) return;
            HrisPayrollPrinter.PreviewRegister(Current, FindForm());
        }

        private void btn_printRemittance_Click(object sender, EventArgs e)
        {
            if (Current == null) return;
            // Remittance sums across every run in the same calendar month
            // (contributions land on the second-cutoff run only), so it needs
            // the full run list, not just the current one.
            HrisPayrollPrinter.PreviewRemittance(Current, _runs, FindForm());
        }

        // ------------------------------------------------------------ search dialog

        private class SearchPayrollDialog : Form
        {
            private readonly TextBox _search = new TextBox { Width = 300 };
            private readonly DataGridView _grid;
            private readonly List<HrisPayrollRunModel> _all;

            public int? SelectedRunId { get; private set; }

            public SearchPayrollDialog(List<HrisPayrollRunModel> runs)
            {
                _all = runs;

                Text = "Payroll Run Search";
                FormBorderStyle = FormBorderStyle.FixedDialog;
                StartPosition = FormStartPosition.CenterParent;
                MaximizeBox = false;
                MinimizeBox = false;
                ClientSize = new System.Drawing.Size(640, 430);

                _grid = new DataGridView
                {
                    Location = new System.Drawing.Point(15, 50),
                    Size = new System.Drawing.Size(610, 320),
                    ReadOnly = true,
                    AllowUserToAddRows = false,
                    RowHeadersVisible = false,
                    SelectionMode = DataGridViewSelectionMode.FullRowSelect,
                    MultiSelect = false,
                    AutoGenerateColumns = false
                };
                _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "id", Visible = false });
                _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "periodStart", HeaderText = "PERIOD START", Width = 110 });
                _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "periodEnd", HeaderText = "PERIOD END", Width = 110 });
                _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "status", HeaderText = "STATUS", Width = 90 });
                _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "employees", HeaderText = "EMPLOYEES", Width = 90 });
                _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "net", HeaderText = "TOTAL NET", Width = 110 });
                _grid.CellDoubleClick += (s, e) => { if (e.RowIndex >= 0) Choose(); };

                var searchLabel = new Label { Text = "SEARCH", Location = new System.Drawing.Point(15, 20), AutoSize = true };
                _search.Location = new System.Drawing.Point(80, 17);
                _search.TextChanged += (s, e) => Refill();

                var select = new Button { Text = "Select", Width = 90, Location = new System.Drawing.Point(430, 385) };
                select.Click += (s, e) => Choose();
                var cancel = new Button { Text = "Cancel", DialogResult = DialogResult.Cancel, Width = 90, Location = new System.Drawing.Point(535, 385) };

                Controls.Add(searchLabel);
                Controls.Add(_search);
                Controls.Add(_grid);
                Controls.Add(select);
                Controls.Add(cancel);
                AcceptButton = select;
                CancelButton = cancel;

                Refill();
            }

            private void Choose()
            {
                if (_grid.SelectedRows.Count == 0) return;
                SelectedRunId = Convert.ToInt32(_grid.SelectedRows[0].Cells["id"].Value);
                DialogResult = DialogResult.OK;
            }

            private void Refill()
            {
                string term = _search.Text.Trim();
                var matches = string.IsNullOrEmpty(term)
                    ? _all
                    : _all.Where(x =>
                        Has(x.PeriodStart, term) || Has(x.PeriodEnd, term)
                        || Has(x.Status, term) || Has(x.Notes, term)).ToList();

                _grid.Rows.Clear();
                foreach (var run in matches)
                {
                    _grid.Rows.Add(run.Id, run.PeriodStart, run.PeriodEnd, run.Status,
                        run.EmployeeCount, run.TotalNet.ToString("n2"));
                }
            }

            private static bool Has(string value, string term)
            {
                return value != null && value.IndexOf(term, StringComparison.OrdinalIgnoreCase) >= 0;
            }
        }
    }
}
